// ====== USERS TEST ======
GET http://localhost:5000/users
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "Admin",
    "password" : "123456",
    "confPassword" : "123456"
}
###
DELETE http://localhost:5000/users
Content-Type: application/json

{
    "username" : "Admin",
    "password" : "123456",
    "confPassword" : "123456"
}
###
// ====== LOGIN =======
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Admin",
    "password" : "123456"
}
// ======= Achievement ========
###
GET http://localhost:5000/achievement
###
GET http://localhost:5000/achievement/name?nameAchievement=Lulus Pelatihan
###
POST http://localhost:5000/achievement
Content-Type: application/json

{
    "imageAchievement": "UTSchool.jpg",
    "nameAchievement": "testing",
    "dateAchievement": "2026-03-20",
    "typeAchievement": "Sertifikat"
}
###
DELETE http://localhost:5000/achievement
Content-Type: application/json

{
    "nameAchievement" : "Lulus Pelatihan"
}
###
PUT http://localhost:5000/achievement
Content-Type: application/json

{
    "oldName" : "Lulus pelatihan UT School",
    "imageAchievement" : "UTSchool.jpg",
    "nameAchievement" : "Lulus Pelatihan",
    "dateAchievement" : "2026-03-20",
    "typeAchievement" : "Sertifikat"
}

//=========== CONTACT ME ============
###
GET http://localhost:5000/contactMe
###
GET http://localhost:5000/contactMe/name?yourName=Rozi Test 
###
POST http://localhost:5000/contactMe
Content-Type: application/json

{
    "yourName": "Rozi Test",
    "email": "rozimunir@gmail.com",
    "subject": "Testing",
    "message": "Testing"
}
###
DELETE http://localhost:5000/contactMe
Content-Type: application/json

{
    "email" : "test@gmail.com"
}
###
PUT http://localhost:5000/contactMe
Content-Type: application/json

{
    "oldEmail" : "rozimunir@gmail.com",
    "yourName" : "Secret Name",
    "email" : "test@gmail.com",
    "subject" : "testing",
    "message" : "testing"
}
31972456

// ============ PROJECT ============
###
GET http://localhost:5000/project
###
GET http://localhost:5000/project/name?nameProject=coba
###
GET http://localhost:5000/project/69f2e666a7ff58c2ea8a0522
###
POST http://localhost:5000/project
Content-Type: application/json

{
    "thumbnail":"test.jpg",
    "nameProject":"coba",
    "overview":"overview",
    "feature":"feature",
    "documentation":[0],
    "techStack":[0],
    "duration":"duration",
    "status":["Pending"],
    "typeProject":"typeProject"
}
###
DELETE http://localhost:5000/project
Content-Type: application/json

{
    "nameProject": "cobacoba"
}
###
PUT http://localhost:5000/project
Content-Type: application/json

{
    "oldNameProject": "testing",
    "thumbnail":"cobacoba",
    "nameProject":"cobacoba",
    "overview":"cobacoba",
    "feature":"cobacoba",
    "documentation":[],
    "techStack":[],
    "duration":"1 day",
    "status":["Complete"],
    "typeProject":"cobacoba"
}

// ============= TECH STACK =============

###
GET http://localhost:5000/techStack
###
GET http://localhost:5000/techStack/name?name=nodejs
###
GET http://localhost:5000/techStack/69f44e9f35a61afd14a4baac
###
POST http://localhost:5000/techStack
Content-Type: application/json

{
    "name": "string",
    "icon": "nodejs.jpg",
    "projectId": null
}

###
DELETE http://localhost:5000/techStack
Content-Type: application/json

{
    "name":"testing"
}

###
PUT http://localhost:5000/techStack
Content-Type: application/json

{
    "oldName": "react",
    "name": "testing",
    "icon": "testing",
    "projectId": null
}

// ============= EDUCATION ============

###
GET http://localhost:5000/education
###
GET http://localhost:5000/education/name?institution=coba
###
GET http://localhost:5000/education/69f5f2b626b6ca0706dd2049
###
POST http://localhost:5000/education
Content-Type: application/json

{
    "institution": "coba",
    "major": "coba",
    "startDate": "2025-03-20",
    "endDate" : "2026-06-21",
    "description": "coba"
}
###
DELETE http://localhost:5000/education
Content-Type: application/json

{
    "institution": "coba"
}
###
PUT http://localhost:5000/education
Content-Type: application/json

{
    "oldInstitution": "testing",
    "major": "cobacoba",
    "institution": "cobacoba",
    "startDate": "2000-05-01",
    "endDate": "2005-07-09",
    "description": "cobacoba"
}

// ============ DOCUMENTATION ===========
###
GET http://localhost:5000/documentation
###
GET http://localhost:5000/documentation/name?name=testing
###
GET http://localhost:5000/documentation/69f715bea5551fa998a35d87
###
POST http://localhost:5000/documentation
Content-Type: application/json

{
    "name": "coba",
    "imageUrl": "coba"
}
###
DELETE http://localhost:5000/documentation
Content-Type: application/json

{
    "name": "coba"
}
###
PUT http://localhost:5000/documentation
Content-Type: application/json

{
    "oldName": "testing",
    "name": "cobacoba",
    "imageUrl": "cobacoba"
}